### ISSUE TITLE
table: Add a setting for "Commit Invalid Segment" to include a literal space

### ISSUE THREAD

**Issue by eternaleye** [fcitx/fcitx5-chinese-addons#151]
When committing an invalid segment while using the LaTeX table, it's often because a sequence in the text _happens_ to start the same way as a LaTeX sequence does (such as an underscore), without actually being a valid LaTeX sequence. When this occurs, the space bar is often pressed not as an intentional interaction with the input method, but as part of the normal flow of text. When the input method then consumes the space in the act of committing the invalid segment, this causes the text to not match the user's intent.

This is not affected by "Auto select when no match is found"; that simply changes _when_ the described event occurs. With the following changes from the defaults (see #150 for why):

- Commit invalid segment: true
- Limit length of selecting only candidate: `1`
- Exact Match: true
- Learning: false

the behavior is as follows:

- Auto select when no match is found: `-1`:
    - Typing `_foo_` results in a preedit of `_foo_`, and a subsequent space is consumed by committing it.
- Auto select when no match is found: `0`:
    - The same as `-1`
- Auto select when no match is found: `1`:
    - Typing `_foo_` results in a committed input of `_foo` and a preedit of `_`, and a subsequent space is consumed by committing it.

**Comment by wengxt** [comment]
Though we add a new option in ddd828048a386b988317d23d99b1797bad340cbc, it's actually still tricky about what space will do after the change. Because space is not a valid code in latex table, it will still trigger the candidate selection, but it will also commit a space (difference).

E.g. when you type "\lam" and space without exact match, it will commit "λ " based on the logic: whenever a key that is not code typed, select current candidate and then by pass the key.

You may need to make "space" a valid code in the KeyCode= line in latex.txt and regenerate it (need to put space in the middle otherwise it will be stripped) to get what you want.

**Comment by eternaleye** [comment]
Mm, that's fair. I'll play around with it and see how it shakes out!
