### ISSUE TITLE
meet some err whem comile under fedora 33

### ISSUE THREAD

**Issue by iysheng** [fcitx/fcitx5-chinese-addons#39]
I want to install fcitx5 with chinese input method under fedora33 preview version. I install fcitx5 relate package under offcial repo **and i don't know why there is no fcitx5-chinese-addons package**.  When i choose pinyin methord ,it's not work, so i though maybe i should compile the package and manual install it, so i clone this repo , After i config the pro, when i try to make it. i meet some err relate to **ToolTipAnnotation**, like :
```
fcitx5-chinese-addons/im/table/ime.h:93:32: error: ‘ToolTipAnnotation’ was not declared in this scope; did you mean ‘FontAnnota    tion’?
```
what maybe wrong? should i recompile **libime** or sth others??

**Comment by wengxt** [comment]
your fcitx5 is simply too old.

**Comment by karuboniru** [comment]
FYI, a recent fcitx5 release (including chinese-addons) for fedora 33 is [here] (you can install them by the instructions in bodhi), I can't push them to stable since we are during beta freeze.

And for those fedora specific problem reports, they should go to [Red Hat bugzilla](bugzilla.redhat.com), where more specific suggestion will be available.

[here]: https://bodhi.fedoraproject.org/updates/FEDORA-2020-3b955a93b6

**Comment by iysheng** [comment]
thanks, I have installed the package **fcitx5-chinese-addons** success obey the link you mentioned.😊
